# fly.toml app configuration file generated for immunity-cron on 2026-04-25T20:45:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'immunity-cron'
primary_region = 'yyz'

[build]
  dockerfile = '.flyio/Dockerfile.app'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_TIMEZONE = 'UTC'
  MODE = 'CRON'

[processes]
  cron = '/usr/local/bin/supercronic /var/www/html/.flyio/crontab'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  processes = ['cron']
